package org.dieschnittstelle.jee.esa.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-05-25T12:57:16.333+02:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://dieschnittstelle.org/jee/esa/jaxws", name = "TouchpointCRUDWebServiceSOAP")
@XmlSeeAlso({org.dieschnittstelle.jee.esa.crm.entities.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TouchpointCRUDWebServiceSOAP {

    @WebMethod
    @WebResult(name = "readAllTouchpointsResponse", targetNamespace = "http://dieschnittstelle.org/jee/esa/jaxws", partName = "readAllTouchpointsResponse")
    public org.dieschnittstelle.jee.esa.crm.entities.AbstractTouchpointArray readAllTouchpoints();

    @WebMethod
    @WebResult(name = "createTouchpointResponse", targetNamespace = "http://dieschnittstelle.org/jee/esa/jaxws", partName = "createTouchpointResponse")
    public org.dieschnittstelle.jee.esa.crm.entities.AbstractTouchpoint createTouchpoint(
        @WebParam(partName = "createTouchpoint", name = "createTouchpoint", targetNamespace = "http://dieschnittstelle.org/jee/esa/jaxws")
        org.dieschnittstelle.jee.esa.crm.entities.AbstractTouchpoint createTouchpoint
    );

    @WebMethod
    @WebResult(name = "deleteTouchpointResponse", targetNamespace = "http://dieschnittstelle.org/jee/esa/jaxws", partName = "deleteTouchpointResponse")
    public boolean deleteTouchpoint(
        @WebParam(partName = "deleteTouchpoint", name = "deleteTouchpoint", targetNamespace = "http://dieschnittstelle.org/jee/esa/jaxws")
        int deleteTouchpoint
    );
}
